package com.ly.model.eo;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 15 15:33:21 CST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XsxxglXsjbxxImpl extends EntityImpl {

    public static final ADFLogger LOGGER =
        ADFLogger.createADFLogger(XsxxglXsjbxxImpl.class);

    /**
     * Validation method for Xsid.
     */
    public boolean validateXsid(String xsid) {
        //校验学生id长度
        if (xsid.length() != 11) {
            LOGGER.info("============校验学生id长度不对===========");
            return false;
        }
        LOGGER.info("============校验学生id长度为11，校验通过===========");
        return true;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Xsid {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXsid();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXsid((String)value);
            }
        },
        Bjdm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getBjdm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setBjdm((String)value);
            }
        },
        Zzmm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getZzmm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setZzmm((String)value);
            }
        },
        Byzxdq {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getByzxdq();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setByzxdq((String)value);
            }
        },
        Bdzy {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getBdzy();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setBdzy((String)value);
            }
        },
        Kl {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getKl();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setKl((String)value);
            }
        },
        Syd {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getSyd();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setSyd((String)value);
            }
        },
        Jg {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getJg();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setJg((String)value);
            }
        },
        Hkszd {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getHkszd();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setHkszd((String)value);
            }
        },
        Mz {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getMz();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setMz((String)value);
            }
        },
        Lqzy {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getLqzy();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setLqzy((String)value);
            }
        },
        Ksh {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getKsh();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setKsh((String)value);
            }
        },
        Xm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXm((String)value);
            }
        },
        Xmpy {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXmpy();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXmpy((String)value);
            }
        },
        Cym {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getCym();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setCym((String)value);
            }
        },
        Xb {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXb();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXb((String)value);
            }
        },
        Sfzh {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getSfzh();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setSfzh((String)value);
            }
        },
        Ykt {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getYkt();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setYkt((String)value);
            }
        },
        Mm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getMm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setMm((String)value);
            }
        },
        Csrq {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getCsrq();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setCsrq((String)value);
            }
        },
        Xx {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXx();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXx((String)value);
            }
        },
        Nf {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getNf();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setNf((String)value);
            }
        },
        Zslb {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getZslb();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setZslb((String)value);
            }
        },
        Xppath {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXppath();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXppath((String)value);
            }
        },
        Sfyj {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getSfyj();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setSfyj((String)value);
            }
        },
        Kslb {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getKslb();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setKslb((String)value);
            }
        },
        Hkxz {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getHkxz();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setHkxz((String)value);
            }
        },
        Sfhp {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getSfhp();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setSfhp((String)value);
            }
        },
        Byzx {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getByzx();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setByzx((String)value);
            }
        },
        Lxdh {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getLxdh();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setLxdh((String)value);
            }
        },
        Jtdh {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getJtdh();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setJtdh((String)value);
            }
        },
        Jtdz {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getJtdz();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setJtdz((String)value);
            }
        },
        Yzbm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getYzbm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setYzbm((String)value);
            }
        },
        Dzyx {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getDzyx();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setDzyx((String)value);
            }
        },
        Jkzk {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getJkzk();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setJkzk((String)value);
            }
        },
        Fzjl {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getFzjl();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setFzjl((String)value);
            }
        },
        Bkyy {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getBkyy();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setBkyy((String)value);
            }
        },
        Rxsj {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getRxsj();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setRxsj((String)value);
            }
        },
        Bysj {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getBysj();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setBysj((String)value);
            }
        },
        Xh {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXh();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXh((String)value);
            }
        },
        Bj {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getBj();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setBj((String)value);
            }
        },
        Cjsj {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getCjsj();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setCjsj((Date)value);
            }
        },
        Xgsj {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXgsj();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXgsj((Date)value);
            }
        },
        Xydm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXydm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXydm((String)value);
            }
        },
        Xqdm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXqdm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXqdm((String)value);
            }
        },
        Fdyxm {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getFdyxm();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setFdyxm((String)value);
            }
        },
        Fdygh {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getFdygh();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setFdygh((String)value);
            }
        },
        Xjzt {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getXjzt();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setXjzt((String)value);
            }
        },
        Zszt {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getZszt();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setZszt((String)value);
            }
        },
        Sfydr {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getSfydr();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setSfydr((String)value);
            }
        },
        Sfytb {
            public Object get(XsxxglXsjbxxImpl obj) {
                return obj.getSfytb();
            }

            public void put(XsxxglXsjbxxImpl obj, Object value) {
                obj.setSfytb((String)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XsxxglXsjbxxImpl object);

        public abstract void put(XsxxglXsjbxxImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int XSID = AttributesEnum.Xsid.index();
    public static final int BJDM = AttributesEnum.Bjdm.index();
    public static final int ZZMM = AttributesEnum.Zzmm.index();
    public static final int BYZXDQ = AttributesEnum.Byzxdq.index();
    public static final int BDZY = AttributesEnum.Bdzy.index();
    public static final int KL = AttributesEnum.Kl.index();
    public static final int SYD = AttributesEnum.Syd.index();
    public static final int JG = AttributesEnum.Jg.index();
    public static final int HKSZD = AttributesEnum.Hkszd.index();
    public static final int MZ = AttributesEnum.Mz.index();
    public static final int LQZY = AttributesEnum.Lqzy.index();
    public static final int KSH = AttributesEnum.Ksh.index();
    public static final int XM = AttributesEnum.Xm.index();
    public static final int XMPY = AttributesEnum.Xmpy.index();
    public static final int CYM = AttributesEnum.Cym.index();
    public static final int XB = AttributesEnum.Xb.index();
    public static final int SFZH = AttributesEnum.Sfzh.index();
    public static final int YKT = AttributesEnum.Ykt.index();
    public static final int MM = AttributesEnum.Mm.index();
    public static final int CSRQ = AttributesEnum.Csrq.index();
    public static final int XX = AttributesEnum.Xx.index();
    public static final int NF = AttributesEnum.Nf.index();
    public static final int ZSLB = AttributesEnum.Zslb.index();
    public static final int XPPATH = AttributesEnum.Xppath.index();
    public static final int SFYJ = AttributesEnum.Sfyj.index();
    public static final int KSLB = AttributesEnum.Kslb.index();
    public static final int HKXZ = AttributesEnum.Hkxz.index();
    public static final int SFHP = AttributesEnum.Sfhp.index();
    public static final int BYZX = AttributesEnum.Byzx.index();
    public static final int LXDH = AttributesEnum.Lxdh.index();
    public static final int JTDH = AttributesEnum.Jtdh.index();
    public static final int JTDZ = AttributesEnum.Jtdz.index();
    public static final int YZBM = AttributesEnum.Yzbm.index();
    public static final int DZYX = AttributesEnum.Dzyx.index();
    public static final int JKZK = AttributesEnum.Jkzk.index();
    public static final int FZJL = AttributesEnum.Fzjl.index();
    public static final int BKYY = AttributesEnum.Bkyy.index();
    public static final int RXSJ = AttributesEnum.Rxsj.index();
    public static final int BYSJ = AttributesEnum.Bysj.index();
    public static final int XH = AttributesEnum.Xh.index();
    public static final int BJ = AttributesEnum.Bj.index();
    public static final int CJSJ = AttributesEnum.Cjsj.index();
    public static final int XGSJ = AttributesEnum.Xgsj.index();
    public static final int XYDM = AttributesEnum.Xydm.index();
    public static final int XQDM = AttributesEnum.Xqdm.index();
    public static final int FDYXM = AttributesEnum.Fdyxm.index();
    public static final int FDYGH = AttributesEnum.Fdygh.index();
    public static final int XJZT = AttributesEnum.Xjzt.index();
    public static final int ZSZT = AttributesEnum.Zszt.index();
    public static final int SFYDR = AttributesEnum.Sfydr.index();
    public static final int SFYTB = AttributesEnum.Sfytb.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XsxxglXsjbxxImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.ly.model.eo.XsxxglXsjbxx");
    }

    /**
     * Gets the attribute value for Xsid, using the alias name Xsid.
     * @return the Xsid
     */
    public String getXsid() {
        return (String)getAttributeInternal(XSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xsid.
     * @param value value to set the Xsid
     */
    public void setXsid(String value) {
        setAttributeInternal(XSID, value);
    }

    /**
     * Gets the attribute value for Bjdm, using the alias name Bjdm.
     * @return the Bjdm
     */
    public String getBjdm() {
        return (String)getAttributeInternal(BJDM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bjdm.
     * @param value value to set the Bjdm
     */
    public void setBjdm(String value) {
        setAttributeInternal(BJDM, value);
    }

    /**
     * Gets the attribute value for Zzmm, using the alias name Zzmm.
     * @return the Zzmm
     */
    public String getZzmm() {
        return (String)getAttributeInternal(ZZMM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Zzmm.
     * @param value value to set the Zzmm
     */
    public void setZzmm(String value) {
        setAttributeInternal(ZZMM, value);
    }

    /**
     * Gets the attribute value for Byzxdq, using the alias name Byzxdq.
     * @return the Byzxdq
     */
    public String getByzxdq() {
        return (String)getAttributeInternal(BYZXDQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Byzxdq.
     * @param value value to set the Byzxdq
     */
    public void setByzxdq(String value) {
        setAttributeInternal(BYZXDQ, value);
    }

    /**
     * Gets the attribute value for Bdzy, using the alias name Bdzy.
     * @return the Bdzy
     */
    public String getBdzy() {
        return (String)getAttributeInternal(BDZY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bdzy.
     * @param value value to set the Bdzy
     */
    public void setBdzy(String value) {
        setAttributeInternal(BDZY, value);
    }

    /**
     * Gets the attribute value for Kl, using the alias name Kl.
     * @return the Kl
     */
    public String getKl() {
        return (String)getAttributeInternal(KL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Kl.
     * @param value value to set the Kl
     */
    public void setKl(String value) {
        setAttributeInternal(KL, value);
    }

    /**
     * Gets the attribute value for Syd, using the alias name Syd.
     * @return the Syd
     */
    public String getSyd() {
        return (String)getAttributeInternal(SYD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Syd.
     * @param value value to set the Syd
     */
    public void setSyd(String value) {
        setAttributeInternal(SYD, value);
    }

    /**
     * Gets the attribute value for Jg, using the alias name Jg.
     * @return the Jg
     */
    public String getJg() {
        return (String)getAttributeInternal(JG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jg.
     * @param value value to set the Jg
     */
    public void setJg(String value) {
        setAttributeInternal(JG, value);
    }

    /**
     * Gets the attribute value for Hkszd, using the alias name Hkszd.
     * @return the Hkszd
     */
    public String getHkszd() {
        return (String)getAttributeInternal(HKSZD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hkszd.
     * @param value value to set the Hkszd
     */
    public void setHkszd(String value) {
        setAttributeInternal(HKSZD, value);
    }

    /**
     * Gets the attribute value for Mz, using the alias name Mz.
     * @return the Mz
     */
    public String getMz() {
        return (String)getAttributeInternal(MZ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mz.
     * @param value value to set the Mz
     */
    public void setMz(String value) {
        setAttributeInternal(MZ, value);
    }

    /**
     * Gets the attribute value for Lqzy, using the alias name Lqzy.
     * @return the Lqzy
     */
    public String getLqzy() {
        return (String)getAttributeInternal(LQZY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lqzy.
     * @param value value to set the Lqzy
     */
    public void setLqzy(String value) {
        setAttributeInternal(LQZY, value);
    }

    /**
     * Gets the attribute value for Ksh, using the alias name Ksh.
     * @return the Ksh
     */
    public String getKsh() {
        return (String)getAttributeInternal(KSH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ksh.
     * @param value value to set the Ksh
     */
    public void setKsh(String value) {
        setAttributeInternal(KSH, value);
    }

    /**
     * Gets the attribute value for Xm, using the alias name Xm.
     * @return the Xm
     */
    public String getXm() {
        return (String)getAttributeInternal(XM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xm.
     * @param value value to set the Xm
     */
    public void setXm(String value) {
        setAttributeInternal(XM, value);
    }

    /**
     * Gets the attribute value for Xmpy, using the alias name Xmpy.
     * @return the Xmpy
     */
    public String getXmpy() {
        return (String)getAttributeInternal(XMPY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xmpy.
     * @param value value to set the Xmpy
     */
    public void setXmpy(String value) {
        setAttributeInternal(XMPY, value);
    }

    /**
     * Gets the attribute value for Cym, using the alias name Cym.
     * @return the Cym
     */
    public String getCym() {
        return (String)getAttributeInternal(CYM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cym.
     * @param value value to set the Cym
     */
    public void setCym(String value) {
        setAttributeInternal(CYM, value);
    }

    /**
     * Gets the attribute value for Xb, using the alias name Xb.
     * @return the Xb
     */
    public String getXb() {
        return (String)getAttributeInternal(XB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xb.
     * @param value value to set the Xb
     */
    public void setXb(String value) {
        setAttributeInternal(XB, value);
    }

    /**
     * Gets the attribute value for Sfzh, using the alias name Sfzh.
     * @return the Sfzh
     */
    public String getSfzh() {
        return (String)getAttributeInternal(SFZH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sfzh.
     * @param value value to set the Sfzh
     */
    public void setSfzh(String value) {
        setAttributeInternal(SFZH, value);
    }

    /**
     * Gets the attribute value for Ykt, using the alias name Ykt.
     * @return the Ykt
     */
    public String getYkt() {
        return (String)getAttributeInternal(YKT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ykt.
     * @param value value to set the Ykt
     */
    public void setYkt(String value) {
        setAttributeInternal(YKT, value);
    }

    /**
     * Gets the attribute value for Mm, using the alias name Mm.
     * @return the Mm
     */
    public String getMm() {
        return (String)getAttributeInternal(MM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mm.
     * @param value value to set the Mm
     */
    public void setMm(String value) {
        setAttributeInternal(MM, value);
    }

    /**
     * Gets the attribute value for Csrq, using the alias name Csrq.
     * @return the Csrq
     */
    public String getCsrq() {
        return (String)getAttributeInternal(CSRQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Csrq.
     * @param value value to set the Csrq
     */
    public void setCsrq(String value) {
        setAttributeInternal(CSRQ, value);
    }

    /**
     * Gets the attribute value for Xx, using the alias name Xx.
     * @return the Xx
     */
    public String getXx() {
        return (String)getAttributeInternal(XX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xx.
     * @param value value to set the Xx
     */
    public void setXx(String value) {
        setAttributeInternal(XX, value);
    }

    /**
     * Gets the attribute value for Nf, using the alias name Nf.
     * @return the Nf
     */
    public String getNf() {
        return (String)getAttributeInternal(NF);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nf.
     * @param value value to set the Nf
     */
    public void setNf(String value) {
        setAttributeInternal(NF, value);
    }

    /**
     * Gets the attribute value for Zslb, using the alias name Zslb.
     * @return the Zslb
     */
    public String getZslb() {
        return (String)getAttributeInternal(ZSLB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Zslb.
     * @param value value to set the Zslb
     */
    public void setZslb(String value) {
        setAttributeInternal(ZSLB, value);
    }

    /**
     * Gets the attribute value for Xppath, using the alias name Xppath.
     * @return the Xppath
     */
    public String getXppath() {
        return (String)getAttributeInternal(XPPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xppath.
     * @param value value to set the Xppath
     */
    public void setXppath(String value) {
        setAttributeInternal(XPPATH, value);
    }

    /**
     * Gets the attribute value for Sfyj, using the alias name Sfyj.
     * @return the Sfyj
     */
    public String getSfyj() {
        return (String)getAttributeInternal(SFYJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sfyj.
     * @param value value to set the Sfyj
     */
    public void setSfyj(String value) {
        setAttributeInternal(SFYJ, value);
    }

    /**
     * Gets the attribute value for Kslb, using the alias name Kslb.
     * @return the Kslb
     */
    public String getKslb() {
        return (String)getAttributeInternal(KSLB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Kslb.
     * @param value value to set the Kslb
     */
    public void setKslb(String value) {
        setAttributeInternal(KSLB, value);
    }

    /**
     * Gets the attribute value for Hkxz, using the alias name Hkxz.
     * @return the Hkxz
     */
    public String getHkxz() {
        return (String)getAttributeInternal(HKXZ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hkxz.
     * @param value value to set the Hkxz
     */
    public void setHkxz(String value) {
        setAttributeInternal(HKXZ, value);
    }

    /**
     * Gets the attribute value for Sfhp, using the alias name Sfhp.
     * @return the Sfhp
     */
    public String getSfhp() {
        return (String)getAttributeInternal(SFHP);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sfhp.
     * @param value value to set the Sfhp
     */
    public void setSfhp(String value) {
        setAttributeInternal(SFHP, value);
    }

    /**
     * Gets the attribute value for Byzx, using the alias name Byzx.
     * @return the Byzx
     */
    public String getByzx() {
        return (String)getAttributeInternal(BYZX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Byzx.
     * @param value value to set the Byzx
     */
    public void setByzx(String value) {
        setAttributeInternal(BYZX, value);
    }

    /**
     * Gets the attribute value for Lxdh, using the alias name Lxdh.
     * @return the Lxdh
     */
    public String getLxdh() {
        return (String)getAttributeInternal(LXDH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lxdh.
     * @param value value to set the Lxdh
     */
    public void setLxdh(String value) {
        setAttributeInternal(LXDH, value);
    }

    /**
     * Gets the attribute value for Jtdh, using the alias name Jtdh.
     * @return the Jtdh
     */
    public String getJtdh() {
        return (String)getAttributeInternal(JTDH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jtdh.
     * @param value value to set the Jtdh
     */
    public void setJtdh(String value) {
        setAttributeInternal(JTDH, value);
    }

    /**
     * Gets the attribute value for Jtdz, using the alias name Jtdz.
     * @return the Jtdz
     */
    public String getJtdz() {
        return (String)getAttributeInternal(JTDZ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jtdz.
     * @param value value to set the Jtdz
     */
    public void setJtdz(String value) {
        setAttributeInternal(JTDZ, value);
    }

    /**
     * Gets the attribute value for Yzbm, using the alias name Yzbm.
     * @return the Yzbm
     */
    public String getYzbm() {
        return (String)getAttributeInternal(YZBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Yzbm.
     * @param value value to set the Yzbm
     */
    public void setYzbm(String value) {
        setAttributeInternal(YZBM, value);
    }

    /**
     * Gets the attribute value for Dzyx, using the alias name Dzyx.
     * @return the Dzyx
     */
    public String getDzyx() {
        return (String)getAttributeInternal(DZYX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dzyx.
     * @param value value to set the Dzyx
     */
    public void setDzyx(String value) {
        setAttributeInternal(DZYX, value);
    }

    /**
     * Gets the attribute value for Jkzk, using the alias name Jkzk.
     * @return the Jkzk
     */
    public String getJkzk() {
        return (String)getAttributeInternal(JKZK);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jkzk.
     * @param value value to set the Jkzk
     */
    public void setJkzk(String value) {
        setAttributeInternal(JKZK, value);
    }

    /**
     * Gets the attribute value for Fzjl, using the alias name Fzjl.
     * @return the Fzjl
     */
    public String getFzjl() {
        return (String)getAttributeInternal(FZJL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fzjl.
     * @param value value to set the Fzjl
     */
    public void setFzjl(String value) {
        setAttributeInternal(FZJL, value);
    }

    /**
     * Gets the attribute value for Bkyy, using the alias name Bkyy.
     * @return the Bkyy
     */
    public String getBkyy() {
        return (String)getAttributeInternal(BKYY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bkyy.
     * @param value value to set the Bkyy
     */
    public void setBkyy(String value) {
        setAttributeInternal(BKYY, value);
    }

    /**
     * Gets the attribute value for Rxsj, using the alias name Rxsj.
     * @return the Rxsj
     */
    public String getRxsj() {
        return (String)getAttributeInternal(RXSJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rxsj.
     * @param value value to set the Rxsj
     */
    public void setRxsj(String value) {
        setAttributeInternal(RXSJ, value);
    }

    /**
     * Gets the attribute value for Bysj, using the alias name Bysj.
     * @return the Bysj
     */
    public String getBysj() {
        return (String)getAttributeInternal(BYSJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bysj.
     * @param value value to set the Bysj
     */
    public void setBysj(String value) {
        setAttributeInternal(BYSJ, value);
    }

    /**
     * Gets the attribute value for Xh, using the alias name Xh.
     * @return the Xh
     */
    public String getXh() {
        return (String)getAttributeInternal(XH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xh.
     * @param value value to set the Xh
     */
    public void setXh(String value) {
        setAttributeInternal(XH, value);
    }

    /**
     * Gets the attribute value for Bj, using the alias name Bj.
     * @return the Bj
     */
    public String getBj() {
        return (String)getAttributeInternal(BJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bj.
     * @param value value to set the Bj
     */
    public void setBj(String value) {
        setAttributeInternal(BJ, value);
    }

    /**
     * Gets the attribute value for Cjsj, using the alias name Cjsj.
     * @return the Cjsj
     */
    public Date getCjsj() {
        return (Date)getAttributeInternal(CJSJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cjsj.
     * @param value value to set the Cjsj
     */
    public void setCjsj(Date value) {
        setAttributeInternal(CJSJ, value);
    }

    /**
     * Gets the attribute value for Xgsj, using the alias name Xgsj.
     * @return the Xgsj
     */
    public Date getXgsj() {
        return (Date)getAttributeInternal(XGSJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xgsj.
     * @param value value to set the Xgsj
     */
    public void setXgsj(Date value) {
        setAttributeInternal(XGSJ, value);
    }

    /**
     * Gets the attribute value for Xydm, using the alias name Xydm.
     * @return the Xydm
     */
    public String getXydm() {
        return (String)getAttributeInternal(XYDM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xydm.
     * @param value value to set the Xydm
     */
    public void setXydm(String value) {
        setAttributeInternal(XYDM, value);
    }

    /**
     * Gets the attribute value for Xqdm, using the alias name Xqdm.
     * @return the Xqdm
     */
    public String getXqdm() {
        return (String)getAttributeInternal(XQDM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xqdm.
     * @param value value to set the Xqdm
     */
    public void setXqdm(String value) {
        setAttributeInternal(XQDM, value);
    }

    /**
     * Gets the attribute value for Fdyxm, using the alias name Fdyxm.
     * @return the Fdyxm
     */
    public String getFdyxm() {
        return (String)getAttributeInternal(FDYXM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fdyxm.
     * @param value value to set the Fdyxm
     */
    public void setFdyxm(String value) {
        setAttributeInternal(FDYXM, value);
    }

    /**
     * Gets the attribute value for Fdygh, using the alias name Fdygh.
     * @return the Fdygh
     */
    public String getFdygh() {
        return (String)getAttributeInternal(FDYGH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fdygh.
     * @param value value to set the Fdygh
     */
    public void setFdygh(String value) {
        setAttributeInternal(FDYGH, value);
    }

    /**
     * Gets the attribute value for Xjzt, using the alias name Xjzt.
     * @return the Xjzt
     */
    public String getXjzt() {
        return (String)getAttributeInternal(XJZT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Xjzt.
     * @param value value to set the Xjzt
     */
    public void setXjzt(String value) {
        setAttributeInternal(XJZT, value);
    }

    /**
     * Gets the attribute value for Zszt, using the alias name Zszt.
     * @return the Zszt
     */
    public String getZszt() {
        return (String)getAttributeInternal(ZSZT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Zszt.
     * @param value value to set the Zszt
     */
    public void setZszt(String value) {
        setAttributeInternal(ZSZT, value);
    }

    /**
     * Gets the attribute value for Sfydr, using the alias name Sfydr.
     * @return the Sfydr
     */
    public String getSfydr() {
        return (String)getAttributeInternal(SFYDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sfydr.
     * @param value value to set the Sfydr
     */
    public void setSfydr(String value) {
        setAttributeInternal(SFYDR, value);
    }

    /**
     * Gets the attribute value for Sfytb, using the alias name Sfytb.
     * @return the Sfytb
     */
    public String getSfytb() {
        return (String)getAttributeInternal(SFYTB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sfytb.
     * @param value value to set the Sfytb
     */
    public void setSfytb(String value) {
        setAttributeInternal(SFYTB, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param xsid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String xsid) {
        return new Key(new Object[] { xsid });
    }


}
