package com.ly.model.am;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 12 17:39:41 CST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StudentAdminAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StudentAdminAMImpl() {
    }

    /**
     * Container's getter for DmjBjxxView1.
     * @return DmjBjxxView1
     */
    public ViewObjectImpl getDmjBjxxView1() {
        return (ViewObjectImpl)findViewObject("DmjBjxxView1");
    }

    /**
     * Container's getter for DmjYxxxView1.
     * @return DmjYxxxView1
     */
    public ViewObjectImpl getDmjYxxxView1() {
        return (ViewObjectImpl)findViewObject("DmjYxxxView1");
    }

    /**
     * Container's getter for DmjZyxxView1.
     * @return DmjZyxxView1
     */
    public ViewObjectImpl getDmjZyxxView1() {
        return (ViewObjectImpl)findViewObject("DmjZyxxView1");
    }

    /**
     * Container's getter for XsxxglXsjbxxView1.
     * @return XsxxglXsjbxxView1
     */
    public ViewObjectImpl getXsxxglXsjbxxView1() {
        return (ViewObjectImpl)findViewObject("XsxxglXsjbxxView1");
    }

    /**
     * Container's getter for GengerStatisLov1.
     * @return GengerStatisLov1
     */
    public ViewObjectImpl getGengerStatisLov1() {
        return (ViewObjectImpl)findViewObject("GengerStatisLov1");
    }
}
